name: Build & test Rust contract

on:
  # We want to trigger the build & test pipelines in every branch.
  # This will help us to detect errors earlier in the development process.
  push:
    # But do no run the pipeline when only `md` files are modified.
    paths-ignore:
      - '**.md'
  # We also want to trigger the pipeline on every PR.
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Disables event tracking consent question, which blocks the CI pipeline
    # For more information, take a look at https://github.com/near/near-cli/blob/master/utils/eventtracking.js
    - run: "mkdir $HOME/.near-config && echo '{\"trackingEnabled\": false, \"trackingAccountID\": false}' > $HOME/.near-config/settings.json"
    - run: rustup target add wasm32-unknown-unknown 
    - run: yarn install --frozen-lockfile
    - run: yarn build:contract
    - run: yarn test:contract
    - run: yarn dev-deploy:contract
    - run: yarn api-test:contract
